name: Publish the released PHAR80

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-22.04

    name: Release PHAR

    steps:
      - name: Extract the tag version
        id: tag
        run: echo ::set-output name=tag::${GITHUB_REF##*v}

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install the dependencies
        run: composer install --prefer-dist --optimize-autoloader --ansi --no-interaction --no-progress --no-suggest --no-scripts

      - name: Create the PHAR file.
        run: ./ai-commit app:build ai-commit80.phar --build-version=${{ steps.tag.outputs.tag }}

      - name: Upload the PHAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: ai-commit80.phar
          path: builds/ai-commit80.phar

      - name: Upload the PHAR to release
        run: gh release upload v${{ steps.tag.outputs.tag }} builds/ai-commit80.phar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cp ai-commit80.phar to ai-commit80
        run: cp builds/ai-commit80.phar builds/ai-commit80

      - name: Commit bump
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: Bump to ${{ github.event.release.name }}
          file_pattern: builds/ai-commit80 CHANGELOG.md