name: Publish the released PHAR

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-22.04

    name: Release PHAR

    steps:
      - name: Extract the tag version
        id: tag
        run: echo ::set-output name=tag::${GITHUB_REF##*v}

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2.5
          extensions: dom, curl, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install the dependencies
        run: composer install --prefer-dist --no-progress

      - name: Create the PHAR file.
        run: ./ai-commit app:build ai-commit --build-version=${{ steps.tag.outputs.tag }}

      - name: Upload the PHAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: ai-commit
          path: builds/ai-commit

      - name: Upload the PHAR to release
        run: gh release upload v${{ steps.tag.outputs.tag }} builds/ai-commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit bump
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: Bump to ${{ github.event.release.name }}
          file_pattern: builds/ai-commit CHANGELOG.md